---
- name: Install Ansible task pre-requisites
  ansible.builtin.apt:
    name:
      - git
      - acl
      - policycoreutils
      - gnupg
      - libsasl2-dev
      - libssl-dev
      - libldap2-dev
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - python3-packaging
      - python3-psycopg2
      - python3-cryptography
    state: present
    update_cache: true
- name: Install Indico Requirements
  ansible.builtin.apt:
    name:
      - rsync
      - tar
      - libpq-dev
      - nginx
      - libxslt1-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - libpcre3-dev
      - libyaml-dev
      - zlib1g-dev
      - libbz2-dev
      - libpango1.0-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - liblzma-dev
      - uuid-dev
      - build-essential
      - redis-server
      - libjpeg-turbo8-dev
    state: present
