---
- name: Run and verify role
  hosts: all
  gather_facts: true
  become: true
  remote_user: localadmin
  vars:
    ansible_port: 2222
    ansible_ssh_private_key_file: "{{ molecule_ephemeral_directory }}/id_molecule"
    ansible_become_password: "password"
  roles:
    - artemis-beta.indico
